name : Run my spring boot application 
on: 
 push:
   branches: 
     - master 
    
jobs:
 build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: set JDK version
        uses: actions/setup-java@v4
      - name: Build and package 
        run: mvn clean install 
        


      



